{{ if .Values.schema.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.component_name }}-schema
spec:
  template:
    spec:
      containers:
        - name: schema-load
          image: public.ecr.aws/w8x4g9h7/roboshop-v3/schema-load
          {{- with .Values.schema.env }}
          env:
            {{- toYaml . | nindent 10 }}
          {{- end }}
      restartPolicy: Never
  backoffLimit: 4
  {{ end }}